<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="qsp-oar4-PC" name="com.acttime.customertest.SampleTest" tests="2" failures="1" timestamp="7 Mar 2019 02:46:29 GMT" time="0.014" errors="0">
  <testcase name="test2" time="0.001" classname="com.acttime.customertest.SampleTest"/>
  <testcase name="test1" time="0.013" classname="com.acttime.customertest.SampleTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [HDF] but found [HDFC],
	expected [] but found [Banglaore]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [HDF] but found [HDFC],
	expected [] but found [Banglaore]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.acttime.customertest.SampleTest.test1(SampleTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.infinitest.testrunner.testng.TestNgRunner.runTest(TestNgRunner.java:82)
	at org.infinitest.testrunner.DefaultRunner.runTest(DefaultRunner.java:60)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- com.acttime.customertest.SampleTest -->
